# Generated by Django 4.2.8 on 2024-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_articolo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='cod_art',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
