# Generated by Django 4.2.8 on 2024-01-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_articolo_cod_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
