# Generated by Django 4.2.8 on 2024-01-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='prezzo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
