# Generated by Django 4.2.8 on 2024-01-11 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='')),
                ('codart', models.CharField(max_length=8)),
                ('descrizione', models.TextField()),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=40)),
                ('data_categoria', models.DateField(auto_now_add=True)),
                ('dettagli', models.TextField()),
                ('articolo_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='vetrina.articolo')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateField(auto_now_add=True)),
                ('contenuto', models.TextField()),
                ('autore_richiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='vetrina.categoria')),
            ],
            options={
                'verbose_name': 'Richiesta',
                'verbose_name_plural': 'Richieste',
            },
        ),
    ]
