# Generated by Django 4.2.8 on 2024-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetrina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='prezzo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
