# Generated by Django 4.2.8 on 2024-01-19 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vetrina', '0002_articolo_prezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oggetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='')),
                ('codart', models.CharField(max_length=8)),
                ('descrizione', models.TextField()),
                ('prezzo', models.FloatField()),
            ],
            options={
                'verbose_name': 'Oggetto',
                'verbose_name_plural': 'Oggetti',
            },
        ),
        migrations.RenameField(
            model_name='richiesta',
            old_name='categoria',
            new_name='categoria_appartenenza',
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('data_tipologia', models.DateField(auto_now_add=True)),
                ('dettagli', models.TextField()),
                ('oggetto_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipologie', to='vetrina.oggetto')),
            ],
            options={
                'verbose_name': 'Tipologia',
                'verbose_name_plural': 'Tipologie',
            },
        ),
        migrations.CreateModel(
            name='Domanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_domanda', models.DateField(auto_now_add=True)),
                ('contenuto', models.TextField()),
                ('autore_domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to=settings.AUTH_USER_MODEL)),
                ('oggetto_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to='vetrina.oggetto')),
                ('tipologia_appartenenza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domande', to='vetrina.tipologia')),
            ],
            options={
                'verbose_name': 'Domanda',
                'verbose_name_plural': 'Domande',
            },
        ),
    ]
