# Generated by Django 4.2.8 on 2024-01-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetrina', '0003_oggetto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='articolo_appartenenza',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='autore_richiesta',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='categoria_appartenenza',
        ),
        migrations.DeleteModel(
            name='Articolo',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Richiesta',
        ),
    ]
