# Generated by Django 4.2.8 on 2024-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contatto', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('oggetto', models.CharField(max_length=20)),
                ('contenuto', models.TextField()),
            ],
        ),
    ]
